# Site settings
title: Smart Home x DevOps
email: 
description: >-
  The story of one Platform Engineer taking his work home with him - and the
  untold suffering it brings.
url: "https://www.homexdevops.com"
github_username:  evoio

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
